version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: .
    command: go run main.go
    volumes:
      - .:/project_one_api
    ports:
      - "8080:8080"
    depends_on:
      - db