
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8080:8080"
    command: /go/api
  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - default